/*
 * Dam Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Dam.JSON;

/**
 * DamBatchUploadAssetsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-29T16:21:33.115087699Z[Etc/UTC]")
public class DamBatchUploadAssetsResponse {
  public static final String SERIALIZED_NAME_PRE_SIGNED_URLS = "preSignedUrls";
  @SerializedName(SERIALIZED_NAME_PRE_SIGNED_URLS)
  private List<String> preSignedUrls;

  public DamBatchUploadAssetsResponse() {
  }

  public DamBatchUploadAssetsResponse preSignedUrls(List<String> preSignedUrls) {
    this.preSignedUrls = preSignedUrls;
    return this;
  }

  public DamBatchUploadAssetsResponse addPreSignedUrlsItem(String preSignedUrlsItem) {
    if (this.preSignedUrls == null) {
      this.preSignedUrls = new ArrayList<>();
    }
    this.preSignedUrls.add(preSignedUrlsItem);
    return this;
  }

   /**
   * Get preSignedUrls
   * @return preSignedUrls
  **/
  @javax.annotation.Nullable
  public List<String> getPreSignedUrls() {
    return preSignedUrls;
  }

  public void setPreSignedUrls(List<String> preSignedUrls) {
    this.preSignedUrls = preSignedUrls;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DamBatchUploadAssetsResponse damBatchUploadAssetsResponse = (DamBatchUploadAssetsResponse) o;
    return Objects.equals(this.preSignedUrls, damBatchUploadAssetsResponse.preSignedUrls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(preSignedUrls);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DamBatchUploadAssetsResponse {\n");
    sb.append("    preSignedUrls: ").append(toIndentedString(preSignedUrls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("preSignedUrls");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to DamBatchUploadAssetsResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DamBatchUploadAssetsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DamBatchUploadAssetsResponse is not found in the empty JSON string", DamBatchUploadAssetsResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DamBatchUploadAssetsResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DamBatchUploadAssetsResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("preSignedUrls") != null && !jsonObj.get("preSignedUrls").isJsonNull() && !jsonObj.get("preSignedUrls").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `preSignedUrls` to be an array in the JSON string but got `%s`", jsonObj.get("preSignedUrls").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DamBatchUploadAssetsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DamBatchUploadAssetsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DamBatchUploadAssetsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DamBatchUploadAssetsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<DamBatchUploadAssetsResponse>() {
           @Override
           public void write(JsonWriter out, DamBatchUploadAssetsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DamBatchUploadAssetsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DamBatchUploadAssetsResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DamBatchUploadAssetsResponse
  * @throws IOException if the JSON string is invalid with respect to DamBatchUploadAssetsResponse
  */
  public static DamBatchUploadAssetsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DamBatchUploadAssetsResponse.class);
  }

 /**
  * Convert an instance of DamBatchUploadAssetsResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

